# This is a basic workflow to help you get started with Actions

name: Deploy Something

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Adding markdown
        run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Adding markdown
          run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
  cleanup:
      name: Cleanup
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Adding markdown
          run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY