# This is a basic workflow to help you get started with Actions

name: Deploy Something

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: install composer
        run: composer install
      - name: Adding markdown
        run: php print.php Build >> $GITHUB_STEP_SUMMARY
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Adding markdown
          run: php print.php deploy >> $GITHUB_STEP_SUMMARY
  cleanup:
      name: Cleanup
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Adding markdown
          run: php print.php Cleanup >> $GITHUB_STEP_SUMMARY